# Generated by Django 4.2.4 on 2023-08-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_rename_bookingdate_booking_bookingdate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="no_of_guests",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="menu",
            name="inventory",
            field=models.IntegerField(),
        ),
    ]
